image: java:8-jdk

cache:
  paths:
    - catan/gradle/wrapper

stages:
  - build
  - test
  - distribute

before_script:
  - cd catan
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test jacocoTestReport

distribute:
  stage: distribute
  script:
    - ./gradlew assembleDist
  artifacts:
    paths:
      - build/distributions/*
