package com.gregswebserver.catan.client.event;

import com.gregswebserver.catan.common.event.InternalEvent;

/**
 * Created by Greg on 1/4/2015.
 * Event generated by user input and used to tell the client what actions to take.
 */
public final class UserEvent extends InternalEvent<UserEventType> {

    public UserEvent(Object origin, UserEventType type, Object payload) {
        super(origin, type, payload);
    }
}
